name: cpp-linter

on:
  push:
    paths:
      - "docs/examples/demo/*"
  pull_request:
    paths:
      - "docs/examples/demo/*"


jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''
          extra-args: '-std=c++20 -Wall'
          files-changed-only: true
          thread-comments: false
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: |
          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
